word_data_app/config/routes.rb
Rails.application.routes.draw do
  resources :base_words
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

word_data_app/app/models/base_word.rb
class BaseWord < ApplicationRecord
  belongs_to :pos, optional: true
  belongs_to :language, optional: true
  has_many :inflections, dependent: :destroy
end

word_data_app/app/controllers/base_words_controller.rb
class BaseWordsController < ApplicationController
  before_action :set_base_word, only: [:show, :edit, :update, :destroy]

  # GET /base_words
  # GET /base_words.json
  def index
    @base_words = BaseWord.all
  end

  # GET /base_words/1
  # GET /base_words/1.json
  def show
    respond_to do |format|
      format.html
      format.json { render json: @base_word}
    end
  end

  # GET /base_words/new
  def new
    @base_word = BaseWord.new
  end

  # GET /base_words/1/edit
  def edit
  end

  # POST /base_words
  # POST /base_words.json
  def create
    @base_word = BaseWord.new(base_word_params)

    respond_to do |format|
      if @base_word.save
        format.html { redirect_to @base_word, notice: 'Base word was successfully created.' }
        format.json { render :show, status: :created, location: @base_word }
      else
        format.html { render :new }
        format.json { render json: @base_word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /base_words/1
  # PATCH/PUT /base_words/1.json
  def update
    respond_to do |format|
      if @base_word.update(base_word_params)
        format.html { redirect_to @base_word, notice: 'Base word was successfully updated.' }
        format.json { render :show, status: :ok, location: @base_word }
      else
        format.html { render :edit }
        format.json { render json: @base_word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /base_words/1
  # DELETE /base_words/1.json
  def destroy
    @base_word.destroy
    respond_to do |format|
      format.html { redirect_to base_words_url, notice: 'Base word was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_base_word
      @base_word = BaseWord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def base_word_params
      params.require(:base_word).permit(:base_word, :pos_id, :frequency, :language_id)
    end
end

word_data_app/app/helpers/base_words_helper.rb
module BaseWordsHelper
end

word_data_app/app/views/base_words/_form.html.erb
<%= form_for(base_word) do |f| %>
  <% if base_word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(base_word.errors.count, "error") %> prohibited this base_word from being saved:</h2>

      <ul>
      <% base_word.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :base_word %>
    <%= f.text_field :base_word %>
  </div>

  <div class="field">
    <%= f.label :pos_id %>
    <%= f.text_field :pos_id %>
  </div>

  <div class="field">
    <%= f.label :frequency %>
    <%= f.number_field :frequency %>
  </div>

  <div class="field">
    <%= f.label :language_id %>
    <%= f.text_field :language_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

word_data_app/app/views/base_words/edit.html.erb
<h1>Editing Base Word</h1>

<%= render 'form', base_word: @base_word %>

<%= link_to 'Show', @base_word %> |
<%= link_to 'Back', base_words_path %>

word_data_app/app/views/base_words/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Base Words</h1>

<table>
  <thead>
    <tr>
      <th>Base word</th>
      <th>Pos</th>
      <th>Frequency</th>
      <th>Language</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @base_words.each do |base_word| %>
      <tr>
        <td><%= base_word.base_word %></td>
        <td><%= base_word.pos %></td>
        <td><%= base_word.frequency %></td>
        <td><%= base_word.language %></td>
        <td><%= link_to 'Show', base_word %></td>
        <td><%= link_to 'Edit', edit_base_word_path(base_word) %></td>
        <td><%= link_to 'Destroy', base_word, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Base Word', new_base_word_path %>

word_data_app/app/views/base_words/new.html.erb
<h1>New Base Word</h1>

<%= render 'form', base_word: @base_word %>

<%= link_to 'Back', base_words_path %>

word_data_app/app/views/base_words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Base word:</strong>
  <%= @base_word.base_word %>
</p>

<p>
  <strong>Pos:</strong>
  <%= @base_word.pos %>
</p>

<p>
  <strong>Frequency:</strong>
  <%= @base_word.frequency %>
</p>

<p>
  <strong>Language:</strong>
  <%= @base_word.language %>
</p>

<%= link_to 'Edit', edit_base_word_path(@base_word) %> |
<%= link_to 'Back', base_words_path %>